### PR TITLE
Build --doc without embed_ephem

### LINKED ISSUE #289: 0.4.2 (Build.rs) causes cargo docs to fail to build
Hello,

we're having an unfortunate and unpredictible little issue. What happens on line 31 in the Build.rs script prevents to generate the documentation of any library that depends on ANISE 0.4.2. Apparently because this runs inside a docker without write permission. [Build failure log example](https://docs.rs/crate/gnss-rtk/0.6.0/builds/1313770). We have two options

- either rework the script to allow this step to fail, which may be tedious to do
- try to see if we can detect that it is a `documentation` run, not a normal run, and this could be totally avoided

[Consequence](https://docs.rs/crate/gnss-rtk/latest)

### PR DESCRIPTION
**Pull request by gwbres**
Fixes #289

### CODE REVIEW

**Comment by ChristopherRabotin** [comment]
I hope this works, but I'm not certain that it will because the docs for ANISE pass successfully and the docs.rs documentation says that by default, none of the features are documented. So I think that it could be a documentation building issue in gnss_rtk. When you build the docs there, do you specify to not build the documentation for the dependent crates?

Also, we shouldn't include the spk validation in the documentation because it's a test specific thing.

**Comment by gwbres** [comment]
hum, quite disturbing 👀 
the Cargo script for gnss-rtk is pretty simple, and does not have documentation options.
It includes "anise 0.4.2" with "embed_ephem" solely. Do we need "metaload" for "embed_ephem" to really work ?

**Comment by ChristopherRabotin** [comment]
I don't think that we need `metaload` for the `embed_ephem` feature.

Interestingly, I don't think that there is a doc specific step in the anise CI, but instead it's documented automagically by crates.io: https://github.com/nyx-space/anise/blob/master/.github/workflows/rust.yml .

**Comment by gwbres** [comment]
> I don't think that we need `metaload` for the `embed_ephem` feature.

it could be useful to double check, because if that is the case, then Cargo.toml is wrong

> but instead it's documented automagically by crates.io: https://github.com/nyx-space/anise/blob/master/.github/workflows/rust.yml .

any publication to crates.io triggers a doc-build --all-features by default (me thinks) which you can customize with Cargo.toml

> Interestingly, I don't think that there is a doc specific step in the anise CI

and i eventually faced issues with that in the RINEX lib. The crate would build fine but not the documentation job triggered by crates.io. I could not remember the exact problem. That's why I had to introduce [these two paragraphs](https://github.com/georust/rinex/blob/main/.github/workflows/rust.yml#L67) to make sure at least we do not release until potential problems are fixed

**Comment by ChristopherRabotin** [comment]
The `embed_ephem` feature only requires the `rust_embed` dependency, it does not require `metaload`: https://github.com/nyx-space/anise/blob/master/anise/Cargo.toml#L61 . The code that embeds the ephems at build time does not use anything from the metaload crate. _However_, it does require `reqwest/blocking`, and that isn't specified in the Cargo.toml. I'll need to fix that, or you could in this PR.

**Pull request merged**
