### PR TITLE
Fix/294 metaload lock

### PR DESCRIPTION
**Pull request by ChristopherRabotin**
# Summary

- Allow automatic deletion of the lock file after 10 tries, preventing a dead lock
- Fix Lagrange CI tests for PRs of non-owners of the repo.

## Architectural Changes

No change

## New Features

No change

## Improvements

Allow automatic deletion of the lock file after 10 tries, preventing a dead lock if the downloading was aborted.

## Bug Fixes

No change

## Testing and validation

None =(

## Documentation

This PR does not primarily deal with documentation changes.

### CODE REVIEW

**Comment by gwbres** [comment]
It seems that anytime I'm using `Almanac::latest` (quickest and easiests) construction method, the cached Moon FK EPA is always discarded (CRC32 differs), download then is always initiated and it regularly fails, so I re-run to pass

**Comment by ChristopherRabotin** [comment]
Even with the latest code merged you get a dead lock? I need to update the CRC because I think I forgot to update it when I built the file.

**Comment by gwbres** [comment]
all my crates use the stable tags now, not branches. I may create a temporary branch for the zepto beta test, because it's huge and important, but it is also too much effort to reindex everything on different versions. I'm quite happy with the latest tags now, we can wait for newer ones

**Comment by ChristopherRabotin** [comment]
Yes, I recommend that you use explicit versions and not branches at the moment. I hope that by the end of September I'll be able to have a stable release of hifitime and ANISE, and then make whatever changes are needed as smaller increments of these stable versions. I really need to get back to hifitime so that version 4 can finally be released, there's just a lot of Python work I have not done yet :-/

**Pull request merged**
